name: writtenbyboxs-api

services:
  postgres:
    image: postgres
    container_name: writtenbyboxs-api-postgres
    environment:
      POSTGRES_DB: writtenbyboxs-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - writtenbyboxs-api_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  writtenbyboxs-api_postgres_data: